name: Decompile DLL

on:
  workflow_dispatch:

jobs:
  decompile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install ILSpy CLI
        run: dotnet tool install --global ilspycmd

      - name: Decompile Assembly
        run: |
          mkdir output
          ~/.dotnet/tools/ilspycmd Assembly-CSharp.dll -p -o output

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: decompiled-source
          path: output
